name: 01a Hola Mundo
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
jobs:
  hola-mundo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:   
    - name: Hola Mundo
      run: echo "Hola Mundo"
