name: 02 - Evento Issue
on: 
    push:
    issues: 
        types: 
            - opened
        
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:   
    - name: Hola Carlos
      run: echo "Hola Carlos"
