name: 05a expresiones
on: 
    push:
       branches: ["main"] 
    workflow_dispatch:    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:   
        - name: Operadores
          run: echo "${{ 2 > 1}}"
        - name: Inspeccionar github
          id: githubContext
          run: echo "${{ toJSON(github)}}"
        - name: Evento y actor
          id: eventoActor
          run: |
            echo "evento disparador: ${{ github.event_name }}" 
            echo "lanzado por: ${{ github.actor }}"
        - name: Filtro de objeto
          id: stepsContext
          run: |
            echo "${{ toJSON(steps) }}"
             echo "${{ join(steps.*.conclusion) }}"