name: 06a - variables y secretos
on:
    push:
       branches: ["main"] 
    workflow_dispatch:    
env: 
  COLOR_PILDORA: ${{ vars.COLOR_PILDORA || 'azul' }}
jobs:
  the-matrix: 
    runs-on: ubuntu-latest
    steps:   
        - name: Eleccion neo
          run: |
            echo "Neo has decidido tomar la pildora: ${{ env.COLOR_PILDORA}}" 
        - name: Saber la verdad
          if: ${{ env.COLOR_PILDORA == 'Roja' }}
          run: |
            echo "Neo, la realizad no es lo que piensas"
            echo "Te dire un secreto: ${{ secrets.TODO_ES_MENTIRA}}"
            echo  ${{ secrets.TODO_ES_MENTIRA}}" | sed 's/./&/g'
        - name: Seguir con tu vida
          if: ${{  env.COLOR_PILDORA == 'Azul'}}
          run: echo "Neo, Sigue con tu vida"