name: 06b - variables entre steps
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  tirada-dados:
    runs-on: ubuntu-latest
    steps:
      - name: Genera número aleatorio
        run: |
          NUM=$((1 + RANDOM % 6))
          echo "NUM_ALEATORIO=$NUM" >> $GITHUB_ENV

      - name: Leer resultado
        run: |
          echo "El valor del dado es: $NUM_ALEATORIO"
